name = "price-guessing"
main = "src/index.ts"
account_id = "2d0c503db7fffc019e4e68578b72d021"
compatibility_date = "2024-10-12"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "PLAYER", id = "66ace9cd5d2b4360aaff55b000a5777e" }
]